# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 52e3f238bcdafb80739b0321445ec9eb087199014676d05bc22e6f39c7b108323793bf95495ca964eb8223deb54d7bd7516e144f371e48dec0a4b28e9ed46b54

test:
  secret_key_base: 8afab327769e2d3dae751f9be86864a0ea085a5dffc58730bf205d0e0910a3d7fe97b94b8d430cab91935d29532853b4c0ecf7f9eddcbe59d4625705432e7ba0

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
